### ISSUE TITLE
Formation of letters

### ISSUE THREAD

**Issue by Bdiwy** [Ab-Alselwi/laravel-arabic-html#4]
i try to use it and when i try to test for example sentance like 'َلْتَكُنْ نِعْمَةُ ٱلرَّبِّ إِلَهِنَا عَلَيْنَا، وَعَمَلَ أَيْدِينَا ثَبِّتْ عَلَيْنَ، وَعَمَلَ أَيْدِينَا ثَبِّتْهُ' or ' ٱية عمرو احمد'
i got error  Undefined array key "ٱ"

is the package support formation of arabic letters

**Comment by chemseddine201** [comment]
> i try to use it and when i try to test for example sentance like 'َلْتَكُنْ نِعْمَةُ ٱلرَّبِّ إِلَهِنَا عَلَيْنَا، وَعَمَلَ أَيْدِينَا ثَبِّتْ عَلَيْنَ، وَعَمَلَ أَيْدِينَا ثَبِّتْهُ' or ' ٱية عمرو احمد' i got error Undefined array key "ٱ"
> 
> is the package support formation of arabic letters

share the full stack traces please.

**Comment by Bdiwy** [comment]
i have an invoice generator and the invoice need to be lines of arabic so i use ur package to handle this and every thing is fine but when i enter a formatting  letters some like "ٱية" i got an error ` Undefined array key "ٱ"`  here is the the snapcode 
![code-snapshot](https://github.com/user-attachments/assets/fe6723c1-be71-406f-90a9-d1330b35321e)
in line 33 when i use ->
toArabicHTML
();

**Comment by chemseddine201** [comment]
Surround your code with try-catch block then print the error on the catch section to provide the full traces.

**Comment by Bdiwy** [comment]
i got Undefined array key "ٱ"
